export interface Credits{
    _id?:string
    custumer_prequalification:string
    score_Bc:number
    No_openAccounts:number
    total_monthlyDebts:number
    monthly_payments:number
    monthly_netIncome:number
    additional_activity:number
    bonds:number
    other:number
    spouse_income:number
    endorsement_income:number
    add_income:number
    house_rent:number
    feeding:number
    gasoline:number
    services:number
    Other:number
    sum_ofExpenses:number
    capacity:number
    brand:string
    hitch:number
    price:number
    financing:number
    mounthly_payment:number
    model:string
    invoice_value:number
    total_financingAmount:number
    termM:string
    annuity:number
    customer_ratingscore:number
    net_capacityscore:number
    payment_capacityscore:number
    payment_capacity:number
    labor_oldscore:number
    sumof_points:number
    id_client:string
    updateAt?:string
    createdAt?:string

}